databases:
  - name: bot
    databaseName: bot
    user: bot

services:
  - type: web
    name: bot
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn bot.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bot
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
