# Generated by Django 3.1 on 2020-08-29 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardReplyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=60)),
                ('board_uri', models.CharField(max_length=200)),
                ('reply', models.TextField()),
                ('activated', models.BooleanField(default=False)),
                ('nl_account_pk', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontPageMonitorJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(default='Frontpage', max_length=60)),
                ('board_uri', models.CharField(default='https://www.nairaland.com/', max_length=200)),
                ('reply', models.TextField()),
                ('activated', models.BooleanField(default=False)),
                ('nl_account_pk', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NairalandAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('has_job', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadReplyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_title', models.CharField(max_length=200)),
                ('reply', models.TextField()),
                ('topic_code', models.PositiveIntegerField()),
                ('activated', models.BooleanField(default=False)),
                ('nl_account_pk', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('account_type', models.CharField(choices=[('st', 'Standard'), ('pr', 'Premium'), ('n', 'None')], default='n', max_length=2)),
                ('license_key', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
