# Generated by Django 3.1 on 2020-10-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_donetopics'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneFPTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=11)),
            ],
        ),
        migrations.RenameModel(
            old_name='DoneTopics',
            new_name='DoneBJTopics',
        ),
    ]
