# Generated by Django 3.1 on 2020-08-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200821_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardreplyjob',
            name='board_id',
        ),
        migrations.AddField(
            model_name='boardreplyjob',
            name='board_uri',
            field=models.CharField(default='http://nairaland.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nairalandaccount',
            name='has_job',
            field=models.BooleanField(default=False),
        ),
    ]
