# Generated by Django 3.1 on 2020-10-19 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20201018_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneTDTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=11)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='donebjtopics',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 12, 21, 36, 32543)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donefptopics',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 12, 21, 55, 736433)),
            preserve_default=False,
        ),
    ]
