# Generated by Django 3.1 on 2020-10-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20201019_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donebjtopics',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='donefptopics',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='donetdtopics',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
