# Generated by Django 3.1 on 2020-08-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_threadreplyjob_thread_uri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PremiumPageReplyJob',
        ),
    ]
