# Generated by Django 3.1 on 2020-08-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_delete_premiumpagereplyjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nairalandaccount',
            name='job_id',
        ),
        migrations.AddField(
            model_name='boardreplyjob',
            name='nl_account_pk',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threadreplyjob',
            name='nl_account_pk',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
