# Generated by Django 3.1 on 2020-10-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20201019_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donetdtopics',
            name='topic',
        ),
    ]
