# Generated by Django 3.1 on 2020-08-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20200825_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardreplyjob',
            name='nl_account_pk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threadreplyjob',
            name='nl_account_pk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
