# Generated by Django 3.1 on 2020-08-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20200825_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageMonitorJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(default='Frontpage', max_length=60)),
                ('board_uri', models.CharField(default='https://www.nairaland.com/', max_length=200)),
                ('reply', models.TextField()),
                ('activated', models.BooleanField(default=False)),
                ('nl_account_pk', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
