# Generated by Django 3.1 on 2020-08-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_frontpagemonitorjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='license_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
